### ISSUE TITLE
Tons of errors when compiling.

### ISSUE THREAD

**Issue by GDokmetas** [efthymios-ks/AVR-HD44780-Library#1]
Warning	6	variable 'p' set but not used [-Wunused-but-set-variable]	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	172	11	AVR_LCD_DENEME3
Warning	11	variable 'p' set but not used [-Wunused-but-set-variable]	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	188	11	AVR_LCD_DENEME3
Error	2	unknown type name 'Point_t'	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	172	3	AVR_LCD_DENEME3
Error	7	unknown type name 'Point_t'	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	188	3	AVR_LCD_DENEME3
Error	12	unknown type name 'Point_t'	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	257	1	AVR_LCD_DENEME3
Error	15	unknown type name 'Point_t'	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	259	2	AVR_LCD_DENEME3
Error	5	request for member 'Y' in something not a structure or union	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	180	20	AVR_LCD_DENEME3
Error	10	request for member 'Y' in something not a structure or union	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	196	20	AVR_LCD_DENEME3
Error	17	request for member 'Y' in something not a structure or union	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	262	3	AVR_LCD_DENEME3
Error	20	request for member 'Y' in something not a structure or union	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	272	5	AVR_LCD_DENEME3
Error	22	request for member 'Y' in something not a structure or union	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	313	19	AVR_LCD_DENEME3
Error	4	request for member 'X' in something not a structure or union	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	180	15	AVR_LCD_DENEME3
Error	9	request for member 'X' in something not a structure or union	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	196	15	AVR_LCD_DENEME3
Error	16	request for member 'X' in something not a structure or union	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	261	3	AVR_LCD_DENEME3
Error	18	request for member 'X' in something not a structure or union	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	269	8	AVR_LCD_DENEME3
Error	19	request for member 'X' in something not a structure or union	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	271	5	AVR_LCD_DENEME3
Error	21	request for member 'X' in something not a structure or union	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	308	19	AVR_LCD_DENEME3
Message	14	previous declaration of 'LCD_getP' was here	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.h	84	9	AVR_LCD_DENEME3
Error	3	incompatible types when initializing type 'int' using type 'POINT_t'	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	172	15	AVR_LCD_DENEME3
Error	8	incompatible types when initializing type 'int' using type 'POINT_t'	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	188	15	AVR_LCD_DENEME3
Warning	23	control reaches end of non-void function [-Wreturn-type]	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	309	1	AVR_LCD_DENEME3
Warning	24	control reaches end of non-void function [-Wreturn-type]	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	314	1	AVR_LCD_DENEME3
Error	13	conflicting types for 'LCD_getP'	C:\Users\Gökhan Dökmetaş\Desktop\ATMEL\ATMEL STUDIO PROJECTS\AVR_LCD_DENEME3\AVR_LCD_DENEME3\HD44780.c	257	9	AVR_LCD_DENEME3
Warning	1	#warning "F_CPU not defined for <util/delay.h>" [-Wcpp]	c:\program files (x86)\atmel\atmel toolchain\avr8 gcc\native\3.4.1061\avr8-gnu-toolchain\avr\include\util\delay.h	90	3	AVR_LCD_DENEME3

**Comment by efthymios-ks** [comment]
Sorry for the late response but I did not get any notification to reply to earlier. 

I assume that you use Atmel Studio by reading your log. Please make sure you follow these three specific steps: 
1. Download the freshly updated library files (**HD44780.c**, **HD44780.h**, **HD44780_Settings.h**, **IO_Macros.h**). 
2. Include all four files into the project solution. 
3. Edit the **HD44780_Settings.h** to fit your requirements.
4. Include **HD44780.h** into the main source code file by inserting`#include "HD44780.h"` at the top.
