### ISSUE TITLE
Doesn't support working without RW

### ISSUE THREAD

**Issue by fuzun** [efthymios-ks/AVR-HD44780-Library#2]
Hello,

I have Arduino UNO board and a shield which has RW pin directly connected to ground.

Arduino library LiquidCrystal works fine without RW pin, so I am asking if there is a shortcut for this library to work without controlling RW.

**Comment by efthymios-ks** [comment]
Try the following and see what happens. Clear the instructions in the LCD_WaitBusy function. It should be empty. Or if you want to keep the instructions just add a return statement in the beginning. 
```
void LCD_WaitBusy()
{
 return; 

 ...
}
```
